version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
    networks:
      - hbase-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50070"]
      interval: 30s
      timeout: 10s
      retries: 3

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
    depends_on:
      namenode:
        condition: service_healthy
    ports:
      - 50075:50075
    networks:
      - hbase-network

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env
    depends_on:
      - datanode
    ports:
      - 8088:8088
    networks:
      - hbase-network

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop2.7.4-java8
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    depends_on:
      - resourcemanager
    networks:
      - hbase-network

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop2.7.4-java8
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    depends_on:
      - resourcemanager
    ports:
      - 8188:8188
    networks:
      - hbase-network

  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
      - 41111:41111
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hbase-standalone.env
    depends_on:
      namenode:
        condition: service_healthy
    networks:
      - hbase-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'status' | /opt/hbase-1.2.6/bin/hbase shell"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  hbase-thrift:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase-thrift
    ports:
      - 9090:9090
      - 9095:9095
    environment:
      SERVICE_PRECONDITION: "hbase:16010"
      HBASE_CONF_hbase_zookeeper_quorum: "hbase"
      HBASE_CONF_hbase_zookeeper_property_clientPort: "2181"
      HBASE_CONF_hbase_client_retries_number: "10"
      HBASE_CONF_hbase_client_pause: "1000"
      HBASE_CONF_hbase_rpc_timeout: "60000"
      HBASE_CONF_hbase_client_operation_timeout: "300000"
    env_file:
      - ./hbase-standalone.env
    command: ["/opt/hbase-1.2.6/bin/hbase", "thrift", "start", "-p", "9090", "--infoport", "9095"]
    depends_on:
      hbase:
        condition: service_healthy
    networks:
      - hbase-network
    restart: on-failure

networks:
  hbase-network:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hbase_data:
  hbase_zookeeper_data:
